ALTER TABLE "Campaign" ADD COLUMN "tension" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "OracleRecord" ADD COLUMN "tensionAtRoll" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "OracleRecord" ADD COLUMN "randomEventTriggered" BOOLEAN NOT NULL DEFAULT false;
